### ISSUE TITLE
[FEATURE] Create an app that allows manually sending transactions with custom Input Data.

### ISSUE THREAD

**Issue by lastperson** [zviadm/celoterminal#116]
Needed for both multisig and simple accounts.

**Comment by zviadm** [comment]
Hey, can you expand a bit more on what you mean by this issue?
Do you want a custom app that allows to send arbitrary transactions to arbitrary contracts?

**Comment by lastperson** [comment]
Imagine there is a contract A with function `deposit() payable` which accepts native CELO as a payment. Right now it is impossible to call that function with Celo Terminal. In order to make it possible, and make it universal there should be an optional Input Data (hex) field when sending CELO. If user puts `0xd0e30db0` (contract.methods.deposit().encodeABI()) in this field and sends a transaction to contract A then deposit function will be executed.

This is the basic functionality that was available in MyEtherWallet, Mist Browser, MetaMask, etc. since the very beginning, because it is the one that makes the wallet complete, and allows the user to interact with any contract assuming he knows how to encode data.

Next step ofcourse would be to add a dynamic UI generation from contract ABI, but that is not required at all.

**Comment by zviadm** [comment]
Some notes:

* The send/receive APP in Celo Terminal is using ERC-20 interface for all tokens. Including for CELO. Compared to Ethereum, Celo comes with a native ERC-20 wrapper even for CELO token so when you are using send/receive APP, CELO is never sent directly as a 'send' call. It is always transferred using the ERC20 'transfer' or 'transferFrom' interface. So this type of functionality wouldn't make sense inside the send/receive app.

* It is possible to build a Celo Terminal app that allows you to enter arbitrary contract address and arbitrary input data to make arbitrary transactions. There are no plans to do this at the moment because it is far too advanced of a use-case and it is way too error-prone. It is probably better to just add this type of functionality just inside 'celocli'. 

* There are plans to add an app that will have 'Etherscan' style read-contract/write-contract functionality for any contract that will have its source code verified. This should serve the use case of allowing users to send more or less arbitrary transactions to any source verified contract. This will also be a bit less error-prone (but still pretty advanced/dangerous because calling random contract functions directly is never that safe). Timeline for this app is probably 4-6 weeks in future, since code verification through sourcify.dev is still being figured out right now.

**Comment by zviadm** [comment]
Next release will contain an "SC Inspector" that will allow interacting with arbitrary contracts as long as their source code is verified on https://sourcify.dev
