### ISSUE TITLE
Support Ledger Ethereum Addresses

### ISSUE THREAD

**Issue by tomasmcm** [zviadm/celoterminal#272]
Metamask only supports the Ethereum Ledger App for any EVM chain. This means, it's not possible to use wallets from the Celo Ledger App with Metamask. On the other hand, Celo Terminal only supports the Celo Ledger App.
If I want to use Celo Terminal to send, swap, mint, ... I need to transfer tokens between the Ethereum-derived wallet and the Celo-derived ones.

I was able to add a wallet from the Ethereum app using the custom path option when importing a wallet.
However, when making a transaction it fails saying "Ledger device: can not connect. Make sure your Ledger device is connected, unlocked, and the Celo app is launched."

Would it be possible to add support for Ethereum Ledger Wallets in Celo Terminal?
Thanks!

**Comment by zviadm** [comment]
Unfortunately this is not easy, and will cause other issues. 
To support Ethereum Ledger addresses, Celo Terminal would need to work with Ethereum Ledger App, since you can't use those addresses with Celo Ledger App. That means for those addresses Celo specific features will never work (like paying for gas with cUSD instead of CELO tokens), so there would have to be a lot of special casing to make sure transactions are crafted differently for Etherem Ledger Addresses vs Celo Ledger Addresses. 

So for now Celo Terminal will only work with Celo Ledger app. If Celo Ledger app starts supporting other derivation paths, that could solve this issue more easily.
